apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-nginx
  namespace: foodable-dev
data:
  nginx.conf: |
    worker_processes  1;
    events { worker_connections 1024; }

    http {
      include       mime.types;
      sendfile      on;
      keepalive_timeout 65;

      server {
        listen 4000;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization     $http_authorization;

        set $auth_up     http://auth:4001;
        set $catalog_up  http://catalog:4002;
        set $orders_up   http://orders:4003;

        location = /healthz { return 200 "ok\n"; }

        location /api/auth/ { proxy_pass $auth_up; }
        location = /api/cart/checkout { proxy_pass $orders_up; }
        location ~* ^/api/offers/[^/]+/reserve$ { proxy_pass $orders_up; }
        location /api/restaurants { proxy_pass $catalog_up; }
        location /api/offers { proxy_pass $catalog_up; }
        location /api/me/ { proxy_pass $catalog_up; }
      }
    }

