apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: foodable-dev
spec:
  template:
    spec:
      serviceAccountName: app-sa
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: asia-southeast1-docker.pkg.dev/tribal-cortex-443513-g5/foodable/catalog:v1
          command: ["sh","-lc","npx prisma migrate deploy --schema=./prisma/schema.prisma"]
          env:
            - name: DATABASE_URL
              valueFrom: { secretKeyRef: { name: app-secrets, key: DATABASE_URL } }
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
          args: ["--port=5432", "tribal-cortex-443513-g5:asia-southeast1:foodable-sql"]
