apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-seed
  namespace: foodable-dev
spec:
  template:
    spec:
      serviceAccountName: app-sa
      restartPolicy: OnFailure
      containers:
        - name: seed
          image: asia-southeast1-docker.pkg.dev/tribal-cortex-443513-g5/foodable/catalog:v1
          command: ["sh","-lc","sleep 5; node prisma/seed.js"]
          env:
            - name: DATABASE_URL
              valueFrom: { secretKeyRef: { name: app-secrets, key: DATABASE_URL } }
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
          args: ["--port=5432", "tribal-cortex-443513-g5:asia-southeast1:foodable-sql"]
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
              ephemeral-storage: "256Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
              ephemeral-storage: "512Mi"
