apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: foodable-dev
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
    - name: http
      port: 4002
      targetPort: 4002

