apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: foodable-dev
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      port: 4000
      targetPort: 4000

